In [2]:
import pandas as pd

bios=pd.read_csv("D:\\Documents\\Programming\\Languages\\Python\\Python Tutorials\\Python-Libraries\\Pandas\\pandas-tutorial\\data\\bios.csv")

bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [3]:
bios.loc[0:6, "born_date"]

0    1886-12-12
1    1969-04-01
2    1898-08-13
3    1895-05-11
4    1878-04-17
5    1970-01-13
6    1969-11-27
Name: born_date, dtype: object

In [4]:
bios.sort_values("born_date")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
62451,62914,William Martin,1828-10-25,Rouen,Seine-Maritime,FRA,France,NaN,NaN,1905-02-25
63109,63579,Ferdinand de Schlatter,1831-02-14,Paris IVe,Paris,FRA,France,NaN,NaN,1907-07-04
11836,11898,"Louis, Comte du Douet de Graville",1831-02-27,Bernières,Seine-Maritime,FRA,France,NaN,NaN,1912-10-12
2235,2245,Thomas Scott,1833-01-03,Warren,Ohio,USA,United States,NaN,NaN,1911-06-23
2220,2230,Samuel Duvall,1836-03-11,Liberty,Indiana,USA,United States,NaN,NaN,1908-09-26
...,...,...,...,...,...,...,...,...,...,...
126484,128839,Werner Fehr,NaN,NaN,NaN,NaN,Switzerland,NaN,NaN,1943-09-08
135275,138438,Aleko Mulos,NaN,NaN,NaN,NaN,Türkiye,NaN,NaN,NaN
135280,138443,Louis Léstienne,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
144129,147802,René Van Damme,NaN,NaN,NaN,NaN,Belgium,NaN,NaN,NaN
144132,147805,Raphael de Ligne,NaN,NaN,NaN,NaN,Belgium,NaN,NaN,NaN

In [5]:
bios.shape

(145500, 10)

In [6]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [7]:
# bios.loc[bios["name"].str.contains("Manas")]
# bios.loc[bios["born_country"]=="IND" & bios["NOC"]=="India"] wrong
# bios[bios["born_country"]=="IND" & bios["NOC"]=="India"] wrong

In [8]:
# bios[bios["born_city"]=="Mumbai" and (bios["NOC"]=="India")]
bios[bios["born_city"]=="Mumbai"]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
279,280,Ali Athar Fyzee,1883-08-28,Mumbai,Maharashtra,IND,India,NaN,NaN,1963-11-03
285,286,Kamlesh Mehta,1960-05-01,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
12923,12994,Frank Weldon,1913-08-02,Mumbai,Maharashtra,IND,Great Britain,175.0,66.0,1993-09-21
14593,14691,Bapoo Malcolm,1912-12-12,Mumbai,Maharashtra,IND,India,NaN,NaN,1982-01-19
18701,18829,Richard Norris,1931-12-10,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,2012-08-25
18728,18856,Frederick Scott,1932-11-29,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,2017-01-01
19018,19151,Ashish Kumar Ballal,1970-10-08,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
23226,23402,Rolf Edling,1943-11-30,Mumbai,Maharashtra,IND,Sweden,196.0,91.0,NaN
33237,33489,Cawas Billimoria,1962-10-25,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
47050,47400,Peter Squires,1936-05-28,Mumbai,Maharashtra,IND,Great Britain,168.0,63.0,2011-09-16
47924,48276,Shrichand Bajaj,1933-10-01,Mumbai,Maharashtra,IND,India,NaN,NaN,2005-07-20
47930,48282,Isaac Mansoor,1929-05-30,Mumbai,Maharashtra,IND,India,NaN,NaN,2006-01-01
53847,54233,David Sopher,1929-02-01,Mumbai,Maharashtra,IND,India,NaN,NaN,2019-02-14
56044,56442,Rory Barrett,1945-12-31,Mumbai,Maharashtra,IND,New Zealand,185.0,110.0,NaN
62023,62479,Harry Jefferson,1849-03-09,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,1918-06-23
68517,69034,Launceston Elliot,1874-06-09,Mumbai,Maharashtra,IND,Great Britain,188.0,102.0,1930-08-08
69609,70130,Manisha Malhotra,1976-09-19,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN
70879,71411,Eddie Sequeira,1942-02-06,Mumbai,Maharashtra,IND,India,172.0,54.0,NaN
72084,72630,Shoichiro Takenaka,1912-09-30,Mumbai,Maharashtra,IND,Japan,158.0,46.0,1997-04-04
82089,82742,Aparna Popat,1978-01-18,Mumbai,Maharashtra,IND,India,160.0,65.0,NaN
83644,84307,John Boyagis,1928-01-26,Mumbai,Maharashtra,IND,Great Britain,NaN,NaN,2020-07-22
90937,91661,Robin D'Abreo,1975-03-03,Mumbai,Maharashtra,IND,Canada,178.0,66.0,NaN
90978,91704,Jude Menezes,1971-08-05,Mumbai,Maharashtra,IND,India,172.0,75.0,NaN
92337,93077,Anjali Vedpathak-Bhagwat,1969-12-05,Mumbai,Maharashtra,IND,India,165.0,53.0,NaN
103745,104738,Deepali Deshpande,1969-08-03,Mumbai,Maharashtra,IND,India,159.0,54.0,NaN
107864,109002,Viren Rasquinha,1980-09-13,Mumbai,Maharashtra,IND,India,170.0,65.0,NaN
119636,121462,Mayookha Johny,1988-04-09,Mumbai,Maharashtra,IND,India,174.0,58.0,NaN
128066,130572,Ayonika Paul,1992-09-23,Mumbai,Maharashtra,IND,India,174.0,74.0,NaN
130375,133059,Keegan Pereira,1991-09-08,Mumbai,Maharashtra,IND,Canada,166.0,59.0,NaN
131627,134441,Devindar Walmiki,1992-05-28,Mumbai,Maharashtra,IND,India,178.0,69.0,NaN
134610,137691,Anice Das,1985-12-31,Mumbai,Maharashtra,IND,Netherlands,170.0,65.0,NaN

In [9]:
bios.query('born_region=="Maharashtra" and NOC=="India"')
bios.query('born_city=="Pune (Poona)" and NOC=="India"')
PuneAth=bios.query('born_city=="Pune (Poona)" and NOC=="India"')

print(PuneAth)
print(type(PuneAth))

        athlete_id             name   born_date     born_city  born_region  \
19002        19135     Eliza Nelson  1956-09-27  Pune (Poona)  Maharashtra
104819      105845  Nikhil Kanetkar  1979-05-13  Pune (Poona)  Maharashtra
118302      119992     Frank Brewin  1909-10-21  Pune (Poona)  Maharashtra
131622      134436   Anirban Lahiri  1987-06-29  Pune (Poona)  Maharashtra

       born_country    NOC  height_cm  weight_kg   died_date
19002           IND  India      160.0        NaN         NaN
104819          IND  India      173.0       63.0         NaN
118302          IND  India        NaN        NaN  1976-04-21
131622          IND  India      175.0        NaN         NaN
<class 'pandas.core.frame.DataFrame'>