# Intro to Dataframes

In [64]:
import pandas as pd

df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"]) 
# columns=[] : add column names (default = 0, 1, 2...)
# index=[] : add names to index (default = 0, 1, 2...)

df.head() # show preview of the dataset (default = 5)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [65]:
df.head(2)

   A  B  C
x  1  2  3
y  4  5  6

In [66]:
df.tail() # show the bottom rows (default = 5)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [67]:
df.index # .index : access the index , .tolist() : turn it into list

Index(['x', 'y', 'z'], dtype='object')

In [68]:
df.info() # .info() : to see information about the data

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [69]:
df.describe() # for quantitative data, show mean, std, ...

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [70]:
df["A"].unique() # show unique (non-repeacted) values in a column

array([1, 4, 7])

In [71]:
df.nunique() # show how many unique numeric values in all or a column

A    3
B    3
C    3
dtype: int64

In [72]:
df.shape # .shape : tell the shape of the data

(3, 3)

# Loading dataframe

In [73]:
# csv file : .read_csv()
coffee = pd.read_csv("./warmup-data/coffee.csv") # can also paste in website links into the ()

coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [79]:
# parquet file : .read_parquet()

# excel file : .read_xlsx() - this will take long